### PR TITLE
Fixes #38

### LINKED ISSUE #38: Add 25 more companies
@riturajjain2000 I want to add it. Please assign me this issue.

### PR DESCRIPTION
**Pull request by Khushi-agarwal**
I have added 25 companies.
Fixes #38

### CODE REVIEW

**Review by riturajjain2000 — CHANGES_REQUESTED** [review]
resolve conflicts

**Comment by Khushi-agarwal** [comment]
@riturajjain2000  resolved the conflicts.Kindly review.

**Comment by riturajjain2000** [comment]
> @riturajjain2000 resolved the conflicts.Kindly review.

They are still there

**Comment by Khushi-agarwal** [comment]
@riturajjain2000 The conflicts came because a pr got merged.But now I have made the changes.Kindly review it.Thanks.

**Comment by Khushi-agarwal** [comment]
@riturajjain2000 it's a request if you could review my pr first before merging any other pr because then it causes merge conflicts which is happening from the past 2days.

**Review by riturajjain2000 — APPROVED** [review]

**Pull request merged**
